Updated topics-results-page
adobe-experience-league/exlm pull request #1141
Opened 2024-08-05 17:39 UTC by hannahhhxu

- Implemented the search page of the desired ratio according to the design.
![Screenshot 2024-08-04 at 10 57 30 PM](https://github.com/user-attachments/assets/bccf4a30-089e-4a33-b6f6-36b0c0958fcd)

- Implemented heading section with the corresponding number of search results shown and total results that change with each page change.  
![Screenshot 2024-08-04 at 10 58 29 PM](https://github.com/user-attachments/assets/8a36e914-427b-4cc3-b801-8dada0165283)

- Made sure the design is mobile and tablet compatible:
    -   Tablet View: 
  ![Screenshot 2024-08-04 at 11 59 03 PM](https://github.com/user-attachments/assets/5fbdb6af-2ca3-42d8-962a-a3690eae3e10)

    -   Mobile View:
  ![Screenshot 2024-08-04 at 11 59 32 PM](https://github.com/user-attachments/assets/78b9e3c1-4bbc-4613-afc1-9a323a1ed340)

- Created the dropdown menu for the tablet and mobile view
  <img width="816" alt="Screenshot 2024-08-05 at 12 09 49 AM" src="https://github.com/user-attachments/assets/247d22cb-b959-45fa-9466-9ebf99836b0e">

- Set the max page limit for the pagination bar to be 100
![Screenshot 2024-08-04 at 10 58 55 PM](https://github.com/user-attachments/assets/dfcbac14-c171-40ef-87b6-57813a9fffd3)

Jira ID: [UGP-9910](https://jira.corp.adobe.com/browse/UGP-9910)

Test URLs:

- Before: [https://UGP-9910--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management](http://localhost:3000/en/topic-results)
- After: http://localhost:3000/en/topic-results

2024-08-06 19:11 UTC, ahmed-musallam requested changes

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/filtered-results/filtered-results.css
> +    padding:0 20px 1px 0;
Do you really need that 1px? always round your values unless it's absolutely neccessary, it does not have to be pixel perfect per design.

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/filtered-results/filtered-results.css
> +    padding: 4px 7px;
Does this realy need to be 4px and 7px? can it be 5 and 10 ?

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/pagination/pagination.css
> +    margin: 16px 0;
can this be 15px?

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/pagination/pagination.css
> +    padding: 3px 10px;
Does this really need be 3px? seems like an odd number?

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/pagination/pagination.css
> +    padding: 3px 10px;
Does this really need be 3px? seems like an odd number?

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/pagination/pagination.css
> +    margin: 0 2px;
Does this really need be 2px? seems like an odd number?

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/pagination/pagination.js
> +  const label = type === 'prev' ? 'Previous' : 'Next';
Value of "Previous" and "Next" labels must be in placeholders, refer my other comments on placeholders

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.css
> +    padding:0, 0, 0, 15px;
Commas not necessary here :)

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.css
> +      margin:8px 0;
margin and padding values seem strange, do they need to be 7px and 8px?

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.css
> +      font-family: "Adobe Clean", adobe-clean, "Source Sans Pro", -apple-system, system-ui, "Segoe UI", roboto, ubuntu, "Trebuchet MS", "Lucida Grande", sans-serif;
this is not necessary --- use --body-font-family var if you really want to. or remove it entirely if not needed.

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.css
> +    color: #4B4B4B;
Is there a variable for this color? look at other colors as well, if there are variables for them, use that instead.

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.css
> +        font-family: "Adobe Clean", adobe-clean, "Source Sans Pro", -apple-system, system-ui, "Segoe UI", roboto, ubuntu, "Trebuchet MS", "Lucida Grande", sans-serif;
same comment as above for font-family

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.js
> +// TODO: We need to grab the translated name of the topic from the topics API
Can we resolve this TODO?

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.js
> +  }
this impl means that this block waits for placeholders to be resolved to do the rest of the work/render.

Instead  use either `decoratePlaceholders` or `createPlaceholderSpan` from scripts.
which will show shimmer loading state for placeholders until resolved and result in faster load time for the block

2024-08-06 19:11 UTC, ahmed-musallam commented on blocks/topic-results/tabs/tabs.js
> +            </li>
a lot of duplication here, this can be simplified.

Use github copilot, ask it to "simplify generation of this HTML string", paste the HTML string, it will give you a response like:

```
const tabs = [
  { placeholder: placeholders?.mostRelevant || 'Most relevant', contentType: '[]' },
  { placeholder: placeholders?.documentation || 'Documentation', contentType: JSON.stringify([CONTENT_TYPES.DOCUMENTATION.MAPPING_KEY]) },
  { placeholder: placeholders?.tutorials || 'Tutorials', contentType: JSON.stringify([CONTENT_TYPES.TUTORIAL.MAPPING_KEY]) },
  { placeholder: placeholders?.community || 'Community', contentType: JSON.stringify([CONTENT_TYPES.COMMUNITY.MAPPING_KEY]) },
  { placeholder: placeholders?.events || 'Events', contentType: JSON.stringify([CONTENT_TYPES.EVENT.MAPPING_KEY]) }
];

const htmlString = tabs.map(tab => `
  <li class="tab-wrapper">
    <input type="button" 
      value="${tab.placeholder}" 
      data-contenttype='${tab.contentType}' 
      data-sortby="${COVEO_SORT_OPTIONS.RELEVANCE}"
    />
  </li>
`).join('');
```

Simpler to read, easier to add new items :)

2024-08-06 19:11 UTC, ahmed-musallam commented on scripts/data-service/coveo/coveo-token-service.js
>        const signedIn = await isSignedInUser();
Is this change necessary? and why?

2024-08-16 17:07 UTC, hannahhhxu commented on blocks/topic-results/filtered-results/filtered-results.css
> +    padding: 4px 7px;
HAHA yes they absolutely can😂 sorry I'll try not to use arbitrary numbers down the line

2024-08-16 17:08 UTC, hannahhhxu commented on blocks/topic-results/tabs/tabs.js
> +            </li>
Thank you for all the suggestions sir - much appreciated!!

2024-08-16 17:09 UTC, hannahhhxu commented on scripts/data-service/coveo/coveo-token-service.js
>        const signedIn = await isSignedInUser();
forgot to uncomment these, thank you for pointing it out!

2024-08-16 17:09 UTC, hannahhhxu commented on blocks/topic-results/tabs/tabs.js
> +// TODO: We need to grab the translated name of the topic from the topics API
Yes working on it!!

2024-09-11 16:35 UTC, merged