Teaser
adobe-experience-league/exlm pull request #115
Opened 2023-11-09 17:36 UTC by msagolj

Teaser for Marketing Pages hosted on AEM using Crosswalk.

XD designs: https://xd.adobe.com/view/9a563c5a-2a14-472a-a802-f6b4f65bb4aa-cf05/grid
Test URLs:

- Before: author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/teaser.html
- After: author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/teaser.html?ref=exlm-9

2023-11-13 17:31 UTC, ahmed-musallam requested changes

2023-11-13 17:31 UTC, ahmed-musallam commented on scripts/editor-support.js
> +          const path = blockItemId.substring(18);
can we parse this as a URL instead and then get the path or "rest" of the url sans the domain?

2023-11-14 10:33 UTC, Buuhuu commented on scripts/editor-support.js
> +          const path = blockItemId.substring(18);
no, its not as easy as that.

```
new URL('urn:aemconnection:https://localhost:4502/foobar')

hash: ""
host: ""
hostname: ""
href: "urn:aemconnection:https://localhost:4502/foobar"
origin: "null"
password: ""
pathname: "aemconnection:https://localhost:4502/foobar"
```

2023-11-14 14:21 UTC, ahmed-musallam commented on scripts/editor-support.js
> +          const path = blockItemId.substring(18);
ok, can we at-leaset use `'urn:aemconnection:'.length` then?

2023-11-14 14:58 UTC, thomsebastin commented on styles/styles.scss
> +  padding: 30px 16px;
Styles from this file is applied both on doc site and marketing site. This change will be applied on both sites (I hope that is not the intent here?). We have a `doc` class on doc site `body` element to differentiate between the two. If this style change is specific to marketing site only, maybe better to style it in a way that gets applied only on marketing site.

2023-11-14 15:30 UTC, msagolj commented on scripts/editor-support.js
> +          const path = blockItemId.substring(18);
moved `urn:aemconnection:` into a const and used its .length property.

2023-11-14 17:12 UTC, msagolj commented on styles/styles.scss
> +  padding: 30px 16px;
Hi @thomsebastin 
> Styles from this file is applied both on doc site and marketing site. 

I understand that this file applies to both. I made this change after merging the main branch and seeing that  `/docs` specific styles where added with a `.docs` CSS selector as you mentioned:

> We have a doc class on doc site body element to differentiate between the two.

regarding:

> This change will be applied on both sites (I hope that is not the intent here?)

Nope that is not the intent :) I thought it would not interfere as your `.docs` based selector on `/docs` pages has higher specificity:

![image](https://github.com/adobe-experience-league/exlm/assets/37147400/212e4b9b-4976-45d7-adba-a41c44d92785)

regarding:
> If this style change is specific to marketing site only,

I might be wrong but here is why i made the change:
- The `/docs` pages have a total left/right padding of 48px (46px from` .docs main` + 2px from `.docs main > div.section`) in mobile view
- The mobile XD designs for the marketing pages show a 16~20 px padding left/right:
![image](https://github.com/adobe-experience-league/exlm/assets/37147400/fdde8378-96be-4d7a-add3-b2d9dad9ca30)

https://xd.adobe.com/view/9a563c5a-2a14-472a-a802-f6b4f65bb4aa-cf05/grid
so i picked 16px as a start as this was the previous value it was set to.

regarding:
> maybe better to style it in a way that gets applied only on marketing site.

My understanding is that:
- all `/fragments` links go to wherever fragments come from :)
- all pages below `/docs` are markdown and get the `body` `.docs` selector applied based on the `/docs` path
- all the rest goes to to AEM aka marketing pages and markting pages will be under many different paths so there no way to apply a selector based on start path.

Maybe we can have a talk about this in the next impediment meeting tomorrow to clarify.

2023-11-15 15:59 UTC, drudolph-cognizant approved these changes

2023-11-15 17:46 UTC, ahmed-musallam approved these changes

2023-11-15 17:46 UTC, merged