EXLM-74 Icon Card Block
adobe-experience-league/exlm pull request #116
Opened 2023-11-10 09:17 UTC by ruhisingh1

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: EXLM-74

Test URLs:

- Before: author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/icon-card.html
- After: author-p122525-e1200861.adobeaemcloud.com/content/exlm-ruhis/global/en/icon-card.html

2023-11-10 16:59 UTC, Buuhuu requested changes

2023-11-10 16:59 UTC, Buuhuu commented on component-definition.json
> +                  "allowedComponents": "icon-card",
This is a detail that will change at some point. We should not refer to the actual "allowed component" here but to a list/filter that defines the allowed components with an id. 

Please use `allowedComponents: "icon-block"` instead. (reads like the "allowed components of icon block").

2023-11-10 16:59 UTC, Buuhuu commented on component-models.json
> +        "name": "cardLinkURL",
This must be `cardLink`, so that `cardLinkText` and `cardLink` can be collapsed into a single `<a href="${cardLink}">${cardLinkText}</a>`

2023-11-11 12:16 UTC, ruhisingh1 commented on component-definition.json
> +                  "allowedComponents": "icon-card",
Done

2023-11-11 12:17 UTC, ruhisingh1 commented on component-models.json
> +        "name": "cardLinkURL",
Done

2023-11-14 10:29 UTC, Buuhuu approved these changes

2023-11-14 11:50 UTC, merged