Bugfix accordion (EXLM-378, 379)
adobe-experience-league/exlm pull request #117
Opened 2023-11-10 10:06 UTC by gauthamksn

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: 

- https://jira.corp.adobe.com/browse/EXLM-378
- https://jira.corp.adobe.com/browse/EXLM-379

Test URLs:

Before: https://main--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content
After: https://bugfix-exlm-83-accordion--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content

2023-11-13 17:37 UTC, ahmed-musallam requested changes

2023-11-13 17:37 UTC, ahmed-musallam commented on blocks/accordion/accordion.scss
> +        margin-right: -5.6px;
Do we really need to do fractions?

2023-11-13 17:37 UTC, ahmed-musallam commented on blocks/accordion/accordion.scss
> +  .note-wrapper div {
this is duplicated

2023-11-13 17:37 UTC, ahmed-musallam commented on blocks/accordion/accordion.scss
> +  .note-wrapper {
this is duplicated

2023-11-13 17:37 UTC, ahmed-musallam commented on blocks/accordion/accordion.css
>    line-height: 25.6px;
do we really need to do fractions ?

2023-11-15 05:02 UTC, thomsebastin approved these changes

2023-11-15 10:14 UTC, tprasad05 approved these changes

2023-11-15 14:15 UTC, ahmed-musallam approved these changes

2023-11-15 14:37 UTC, merged