feat: recommended block ui changes exlm-1992
adobe-experience-league/exlm pull request #1236
Opened 2024-09-03 11:23 UTC by nitin-rachabathuni

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-1992

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.live
- After: https://exlm-1992--exlm--adobe-experience-league.hlx.live

2024-09-04 14:28 UTC, ruhisingh1 commented on blocks/recommended-content/recommended-content.js
> +const ALL_MY_OPTIONS_KEY = 'All my products';
The text "All my products" should be added in placeholders as it will be localized.

2024-09-04 14:32 UTC, ruhisingh1 commented on blocks/recommended-content/recommended-content.js
> +    const interestsUrl = `https://experienceleague.adobe.com/api/interests?page_size=200&sort=Order&lang=${lang}`;
The URL can be moved to getConfig() method inside scripts.js similar to other URLs.

2024-09-04 14:36 UTC, ruhisingh1 commented on scripts/tabbed-card/tabbed-card.js
> +loadCSS(`${window.hlx.codeBasePath}/scripts/tabbed-card/tabbed-card.css`);
loadCSS() is an async function. So probably should be called with await. @noormd08 please confirm.

2024-09-04 14:39 UTC, ruhisingh1 commented on scripts/tabbed-card/tabbed-card.js
> +const convertToTitleCaseAndRemove = (str) => str.replace(/[-\s]/g, '').replace(/\b\w/g, (match) => match.toUpperCase());
The same code/method is added for tabbed-cards block as well. Instead of adding this code at block level, should we move it to scripts.js and call in both these files.

2024-09-04 14:40 UTC, ruhisingh1 commented on scripts/tabbed-card/tabbed-card.js
> +const convertToTitleCaseAndRemove = (str) => str.replace(/[-\s]/g, '').replace(/\b\w/g, (match) => match.toUpperCase());
Also, can we update the file name? we do have another tabbed-cards.js which might cause confusion.

2024-09-05 03:28 UTC, nitin-rachabathuni commented on blocks/recommended-content/recommended-content.js
> +const ALL_MY_OPTIONS_KEY = 'All my products';
done Ruhi

2024-09-05 03:28 UTC, nitin-rachabathuni commented on blocks/recommended-content/recommended-content.js
> +    const interestsUrl = `https://experienceleague.adobe.com/api/interests?page_size=200&sort=Order&lang=${lang}`;
done Ruhi

2024-09-05 03:28 UTC, nitin-rachabathuni commented on scripts/tabbed-card/tabbed-card.js
> +const convertToTitleCaseAndRemove = (str) => str.replace(/[-\s]/g, '').replace(/\b\w/g, (match) => match.toUpperCase());
done Ruhi

2024-09-05 06:05 UTC, noormd08 requested changes
Can you rename this function properly convertToTitleCaseAndRemove?

This is an existing function but not sure what the remove meant for,

2024-09-05 06:11 UTC, nitin-rachabathuni commented
> Can you rename this function properly convertToTitleCaseAndRemove?
> 
> This is an existing function but not sure what the remove meant for,

done Noor

2024-09-05 06:57 UTC, noormd08 approved these changes

2024-09-05 07:05 UTC, merged