DON'T MERGE: Feature/exlm 393 cards abstract
adobe-experience-league/exlm pull request #148
Opened 2023-11-20 11:22 UTC by noormd08

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID:

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/en/curated-cards
- After: https://feature-exlm-393-cards-abstract--exlm--adobe-experience-league.hlx.page/en/curated-cards

2023-11-21 06:47 UTC, ahmed-musallam requested changes

2023-11-21 06:47 UTC, ahmed-musallam commented on styles/styles.css
> +.tooltip {
Does this need to be here? or can we move to the block css?

2023-11-21 06:47 UTC, ahmed-musallam commented on scripts/browse-card/browse-card.js
> +  const contributorElement = document.createDocumentFragment();
See function `htmlToElement` in `header.js` for an easier way to build HTML Element from HTML string (instead of using the API to build all of these elements.)

You can see examples of `htmlToElement` used in `header.js` 

You are free to move `htmlToElement` to `scripts.js` or just copy it as a utility in this file. Either is OK.

2023-11-21 07:10 UTC, Sivaramvt commented on blocks/curated-cards/curated-cards.js
> +/**
Let's mark this as dummy component (FIXME) as this has been put up to show the tech work

2023-11-21 07:18 UTC, Sivaramvt commented on scripts/browse-card/browse-card.js
> +    const dateInfo = new Date(startDate.toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));
Let's add a TODO here to apply localization once region selection is in place

2023-11-21 07:20 UTC, Sivaramvt commented on scripts/browse-card/browse-card.js
> +import { loadCSS } from '../lib-franklin.js';
Lot of code in this file. @noormd08 Let's scrutinize and optimize this.

2023-11-21 07:37 UTC, noormd08 commented on blocks/breadcrumbs/breadcrumbs.css
> -.breadcrumbs > div > div {
This is outdated. @nitin-rachabathuni  has already fixed it.

2023-11-21 08:22 UTC, noormd08 commented on styles/styles.css
> +.tooltip {
This tooltip looks more generic. Yes, we can move to block level if it is specific to component.

2023-11-21 08:22 UTC, noormd08 commented on scripts/browse-card/browse-card.js
> +  const contributorElement = document.createDocumentFragment();
@nitin-rachabathuni Please check this.

2023-11-21 08:23 UTC, noormd08 commented on scripts/browse-card/browse-card.js
> +    const dateInfo = new Date(startDate.toLocaleString('en-US', { timeZone: 'America/Los_Angeles' }));
@nitin-rachabathuni - Please take care of this.

2023-11-21 08:24 UTC, noormd08 commented on scripts/browse-card/browse-card.js
> +import { loadCSS } from '../lib-franklin.js';
@nitin-rachabathuni We see some code repetition. Please optimize, we can discuss and review.

2023-11-22 02:55 UTC, ahmed-musallam requested changes

2023-11-22 13:58 UTC, nitin-rachabathuni commented on scripts/browse-card/browse-card.js
> +  const dayNow = createTag('h6', {}, `${weekday}, ${month} ${dateInfo.getDate()}`);
done @ahmed-musallam

2023-11-23 07:12 UTC, noormd08 commented on styles/styles.css
> +.tooltip {
Tooltip CSS moved to block level, as we identified only in Curated cards for now.

2023-11-23 07:20 UTC, nitin-rachabathuni approved these changes

2023-11-23 07:22 UTC, merged