exlm-287-styles
adobe-experience-league/exlm pull request #155
Opened 2023-11-21 10:55 UTC by adobenitesh

Jira ID: EXLM-287

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://bugfix-exlm-287-styles--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management

2023-11-21 14:35 UTC, ahmed-musallam requested changes

2023-11-21 14:35 UTC, ahmed-musallam commented on blocks/header/header.scss
> +@mixin chevron($thickness: 1.5px) {
Let's not use fractions, please use 2px here.

2023-11-21 14:35 UTC, ahmed-musallam commented on blocks/header/header.scss
> +          & li > a {
There's already a hover state for these items by class, is this neccessary?

2023-11-21 15:00 UTC, adobenitesh commented on blocks/header/header.scss
> +          & li > a {
this is for matching the background-color and border-radius values of submenus items under Learn/Community tab(to fix one of the QA defects)

2023-11-21 15:02 UTC, adobenitesh commented on blocks/header/header.scss
> +@mixin chevron($thickness: 1.5px) {
sure I will revert to 2px, however 2px value is making arrow bit thicker and as per QA that is not matching with XD, this is related to discussion we had today for XD match consideration I have also updated EXLM-287 with details.

2023-11-22 03:00 UTC, ahmed-musallam requested changes

2023-11-22 03:00 UTC, ahmed-musallam commented on blocks/header/header.scss
> +          & li > a {
Can you elaborate? what's special about these items?

2023-11-22 03:01 UTC, ahmed-musallam approved these changes

2023-11-22 05:28 UTC, adobenitesh commented on blocks/header/header.scss
> +          & li > a {
this fix is related to defect no 11 (web) (EXLM-287)
- Hovering style color for sublinks inside learn and community tab should match with XD

![image](https://github.com/adobe-experience-league/exlm/assets/147729087/f3d326d3-703e-4eff-9cf7-29f2c87f68c3)

2023-11-22 06:04 UTC, thomsebastin commented on blocks/header/header.scss
> +          & li > a {
I am merging this PR to move the ticket. @adobenitesh Please discuss this item with @ahmed-musallam and let's handle in a separate PR if a change is required.

2023-11-22 06:04 UTC, merged