feat EXLM-475: implement qualtrics integration with feedback bar
adobe-experience-league/exlm pull request #253
Opened 2023-12-19 16:50 UTC by usman-khalid

This PR implements the Qualtrics integration for the feedback bar.

**Jira ID: [EXLM-475](https://jira.corp.adobe.com/browse/EXLM-475)**

**Testing/Validation:**
Validated that data is available via Qualtrics reporting after submission.

![Screenshot 2023-12-19 at 11 47 27 AM](https://github.com/adobe-experience-league/exlm/assets/9199192/4950cb37-2b4c-490b-958e-c06f45c583ec)

**Test URLs:**
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://feat-exlm-475--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management

2023-12-19 19:13 UTC, ahmed-musallam requested changes

2023-12-19 19:13 UTC, ahmed-musallam commented on scripts/feedback/qualtrics/qualtrics-embed.js
> +export const embedQualtricsSurveyIntercept = (surveyIdPlaceholder) => {
Also, where did this file come from? and what did you specifically update in it?

2023-12-19 19:13 UTC, ahmed-musallam commented on scripts/scripts.js
> +export function convertTextToHTML(responseText) {
this is not necessary, use `htmlToElement` instead.

Since you've already refactored the utils, remove it's usage from the feedback block and use  `htmlToElement` directly ;)

2023-12-20 15:36 UTC, usman-khalid commented on scripts/feedback/qualtrics/qualtrics-embed.js
> +export const embedQualtricsSurveyIntercept = (surveyIdPlaceholder) => {
This snippet came directly from Qualtrics to embed the intercept on the page. I just wrapped it in a function to be able to pass the configurable SurveyID.

2023-12-20 15:36 UTC, usman-khalid commented on scripts/scripts.js
> +export function convertTextToHTML(responseText) {
Updated!

2023-12-20 16:18 UTC, ahmed-musallam approved these changes

2023-12-20 16:37 UTC, merged