EXLM-878 Browse Filters and topics
adobe-experience-league/exlm pull request #332
Opened 2024-01-16 08:42 UTC by ruhisingh1

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: EXLM-878

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse
- After: https://feature-exlm-878--exlm--adobe-experience-league.hlx.live/en/browse

2024-01-16 12:37 UTC, nitin-rachabathuni submitted a review, later dismissed

2024-01-17 05:32 UTC, noormd08 requested changes
If browse-topics is not a separate block, please keep the files directly in the browse-filters folder. The current structure can lead to confusion b/w the blocks and utilities.

2024-01-17 06:01 UTC, noormd08 approved these changes

2024-01-17 08:26 UTC, tprasad05 approved these changes

2024-01-17 08:26 UTC, merged