Feature/ugp 9828 Add titles of previous and next pages below buttons
adobe-experience-league/exlm pull request #378
Opened 2024-01-26 22:16 UTC by vik407

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: UGP-9828 - Add titles of previous and next pages below buttons
As a user viewing docs or tutorials, I want more context on where the next page and previous page buttons will bring me so I can decide if I want to use them or not
<img width="1024" alt="Screenshot 2024-01-26 at 5 15 19 PM" src="https://github.com/adobe-experience-league/exlm/assets/3940/86d55fc0-21de-4e71-abb6-89206dc85b70">

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/authoring-guide-exl/using/markdown/cheatsheet]
- After: [https://feature-ugp-9828--exlm--adobe-experience-league.hlx.page/en/docs/authoring-guide-exl/using/markdown/cheatsheet]

2024-01-30 06:14 UTC, ahmed-musallam requested changes

2024-01-30 06:14 UTC, ahmed-musallam commented on blocks/footer/footer.css
> -  max-width: var(--non-spectrum-footer-max-width);
why did the footer need to changed?

2024-01-30 06:14 UTC, ahmed-musallam commented on blocks/header/header.css
> +  /* header is always white */
not necessary in this PR

2024-01-30 06:14 UTC, ahmed-musallam commented on blocks/icon-block/icon-block.css
> +.icon-block .icon-link::after {
this would impact all icons, right? you only need it for the nex/prev buttons no?

2024-01-30 06:14 UTC, ahmed-musallam commented on styles/sass/_typography.scss
> +.is-secondary {
Where is this used? I did not see this class used anywhere else

2024-02-02 17:50 UTC, vik407 commented on blocks/icon-block/icon-block.css
> +.icon-block .icon-link::after {
Regarding this change, I identified that it already existed in the source SCSS file. When I recompiled the stylesheets, it was flagged as a new change. However, this is not an actual edit I made as part of this task.
The source change was implemented by Thomas Sebastian.
I'm opening this for further discussion to clarify its origin and avoid any confusion.

2024-04-23 16:50 UTC, ahmed-musallam commented
Closing this. OLD and replaced by https://github.com/adobe-experience-league/exlm/pull/784

2024-04-23 16:50 UTC, closed without merging