feature/EXLM-4-header
adobe-experience-league/exlm pull request #39
Opened 2023-10-18 10:40 UTC by adobenitesh

**Jira ID:  (Main Story - EXLM-4)**
https://jira.corp.adobe.com/browse/EXLM-235
https://jira.corp.adobe.com/browse/EXLM-237

**Test URLs:** 

- Before: https://main--exlm--adobe-experience-league.hlx.page/fragments/en/header/topnav
- After: https://feature/EXLM-4-header--exlm--adobe-experience-league.hlx.page/fragments/en/header/topnav

2023-10-19 05:16 UTC, ahmed-musallam requested changes

2023-10-19 05:16 UTC, ahmed-musallam commented on blocks/header/header.js
> +    block.innerHTML = `<div class="exl-topnav-wrapper"><nav class="exl-topnav" aria-label="Main">${topNavContent}</nav></div>`;
create these with `document.createElement`
Then assign the `nav` element the inner HTML. (so you can use the nav element below)

2023-10-19 05:16 UTC, ahmed-musallam commented on blocks/header/header.js
> +    const selectors = [
Can you explain the need for this? seems extremely verbose.
I'd suggest getting the `nav` element, then getting it's children, then doing whatever work you need on the children, like assigning them classes: `exl-navAction` and `exl-navItem large-menu` and so on

2023-10-19 05:16 UTC, ahmed-musallam commented on blocks/header/header.js
> +    block.innerHTML = `<div class="exl-topnav-wrapper"><nav class="exl-topnav" aria-label="Main">${topNavContent}</nav></div>`;
this entire HTML comes from the converter, as is, why not assign classes there?

2023-10-19 05:31 UTC, ahmed-musallam requested changes

2023-10-19 05:31 UTC, ahmed-musallam commented on blocks/header/header.scss
> +    &-navAction {
can me make this `nav-action`

2023-10-19 05:31 UTC, ahmed-musallam commented on blocks/header/header.scss
> +    &-topnav {
Can we avoid this nesting partial class names, this is hard to follow.

make it `exl-topnav` and do the same for other classes

2023-10-19 06:47 UTC, adobenitesh commented on blocks/header/header.js
> +    block.innerHTML = `<div class="exl-topnav-wrapper"><nav class="exl-topnav" aria-label="Main">${topNavContent}</nav></div>`;
Done

2023-10-19 06:47 UTC, adobenitesh commented on blocks/header/header.scss
> +    &-navAction {
Done

2023-10-19 06:47 UTC, adobenitesh commented on blocks/header/header.scss
> +    &-topnav {
Done

2023-10-19 06:49 UTC, adobenitesh commented on blocks/header/header.js
> +    const selectors = [
This is because only specific list of div blocks need to be given '.exl-nav-item' name hence grouping into an array and assigning selector identifier only to specific nav elements.

2023-10-19 06:49 UTC, adobenitesh commented on blocks/header/header.js
> +    const selectors = [
This is because only specific list of div blocks need to be given '.exl-nav-item' name hence grouping into an array and assigning selector identifier only to specific nav elements.

2023-10-20 05:49 UTC, ahmed-musallam requested changes

2023-10-20 05:49 UTC, ahmed-musallam commented on blocks/header/header.js
> +    'https://51837-exlmconverter-dev.adobeioruntime.net/api/v1/web/main/convert/fragments/en/header',
You cannot use the converter path here, you have to get the HTML content via `/fragments/en/header.plain.html`

Converter path can change, and we should not be calling the converter directly anyway, all HTML requests should go through franklin

2023-10-20 05:51 UTC, ahmed-musallam commented
@niteshadobe please take a look at the review items, we cannot call the converter directly

2023-10-26 05:32 UTC, adobenitesh commented
Closing this PR as another PR for similar task already merged.
https://github.com/adobe-experience-league/exlm/pull/55

2023-10-26 05:32 UTC, closed without merging