feat: layout EXLM-224
adobe-experience-league/exlm pull request #40
Opened 2023-10-18 12:28 UTC by nitin-rachabathuni

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-224

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://feature-exlm-224-layout--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet

2023-10-18 12:33 UTC, thomsebastin commented
@nitin-rachabathuni Looks like you have provided the URL to your fork. Could you please generate a preview URL with this repo as base?

2023-10-18 12:38 UTC, thomsebastin requested changes

2023-10-18 12:38 UTC, thomsebastin commented on scripts/scripts.js
> +    if (childDivs.length === 0) {
this does not ensure if there's at least 3 child div elements. Maybe this is is not what you want.

2023-10-18 12:38 UTC, thomsebastin commented on scripts/scripts.js
> +    });
is this change related to this functionality? Why do we need this?

2023-10-18 12:38 UTC, thomsebastin commented on scripts/scripts.js
> +  if (main) {
this check is unnecessary here. This is already done before we reach this point.

2023-10-18 12:50 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  if (main) {
updated..

2023-10-18 12:51 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +    });
removed Thomas

2023-10-18 12:51 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +    if (childDivs.length === 0) {
Updated it.

2023-10-18 12:53 UTC, thomsebastin commented
Looks like the layout is not accurate. You are sending the whole markdown content into both left and right rail. Please send the actual structure that is in [this](https://experienceleague-dev.corp.adobe.com/docs/authoring-guide-exl/using/markdown/cheatsheet.html?lang=en#basic-syntax) page, just the outer divs would do. Please make those changes in the converter side. 

I also see a horizontal scrollbar. Please have a look.

2023-10-18 13:02 UTC, nitin-rachabathuni commented
> Looks like the layout is not accurate. You are sending the whole markdown content into both left and right rail. Please send the actual structure that is in [this](https://experienceleague-dev.corp.adobe.com/docs/authoring-guide-exl/using/markdown/cheatsheet.html?lang=en#basic-syntax) page, just the outer divs would do. Please make those changes in the converter side.
> 
> I also see a horizontal scrollbar. Please have a look.

Hi @thomsebastin these template changes are only for test purposes,,  @devisree29 will be working on the template part.

2023-10-18 13:13 UTC, nitin-rachabathuni commented
> @nitin-rachabathuni Looks like you have provided the URL to your fork. Could you please generate a preview URL with this repo as base?

Hi @thomsebastin 
I have updated the URL but the layout will be applied _(required divs are missing in the main tag currently)_ only after @devisree29 changes.

2023-10-19 05:05 UTC, ahmed-musallam requested changes

2023-10-19 05:05 UTC, ahmed-musallam commented on scripts/scripts.js
> +function buildLayout(main) {
Why not do this in CSS?

We are always guaranteed to get 3 divs in doc pages, so let's do this in Pure CSS instead

2023-10-19 06:18 UTC, ahmed-musallam requested changes

2023-10-19 06:18 UTC, ahmed-musallam commented on scripts/scripts.js
> +  main.style.display = 'grid';
Here's an example of how to do the layout we need in css grid:
https://jsfiddle.net/ahmedmusallam/y7ma0rzu/44/

2023-10-19 11:27 UTC, thomsebastin requested changes

2023-10-19 11:27 UTC, thomsebastin commented on scripts/scripts.js
> +  wrapperElement.style.width = '100%';
Can this styles not be part of `wrapper` class?

2023-10-19 11:27 UTC, thomsebastin commented on scripts/scripts.js
> +  expanderElement.classList.add('expanded');
same as previous comment. Let `CSS` take care of this once the class is added.

2023-10-19 11:27 UTC, thomsebastin commented on scripts/scripts.js
> +  }
Can we tackle conditional styles by toggling different class names?

2023-10-19 11:27 UTC, thomsebastin commented on scripts/scripts.js
> +  expanderElement.onclick = () => {
any reason the standard `addEventListener` wont work here?

2023-10-19 11:27 UTC, thomsebastin commented on scripts/scripts.js
> +    main.style.gridTemplateColumns = `${leftSectionWidth} 1fr ${rightSectionWidth}`;
I was hoping for toggle to work with just switch of classnames in JS and having the styles managed in CSS. Can we please try that way. This is too verbose.

2023-10-19 12:04 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +function buildLayout(main) {
Updated, ty Ahmed.

2023-10-19 12:05 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  main.style.display = 'grid';
Ty, updated.

2023-10-19 12:05 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  wrapperElement.style.width = '100%';
Moved all the possible styles to CSS @thomsebastin

2023-10-19 12:05 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  }
done @thomsebastin

2023-10-19 12:05 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  }
Moved all the possible styles to CSS

2023-10-19 12:05 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +    main.style.gridTemplateColumns = `${leftSectionWidth} 1fr ${rightSectionWidth}`;
Moved all the possible styles to CSS @thomsebastin

2023-10-19 12:29 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  expanderElement.classList.add('expanded');
Moved all the possible styles to CSS

2023-10-19 12:33 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  expanderElement.onclick = () => {
It works @thomsebastin , have updated

2023-10-20 11:31 UTC, Sivaramvt commented on scripts/scripts.js
> +  toggleElement.innerHTML = `<img src="https://experienceleague-dev.corp.adobe.com/assets/img/left-rail-open.svg">`;
@nitin-rachabathuni This may not be right. We should be placing this svg in our franklin repo.

2023-10-20 13:56 UTC, thomsebastin commented on scripts/scripts.js
> +        rightSectionWidth = main?.children?.[2]?.classList?.contains(
@nitin-rachabathuni I think you can drop all the `?` from main as that check is made prior to reaching this function.

2023-10-25 06:09 UTC, thomsebastin commented on scripts/scripts.js
> +  toggleElement.innerHTML = `<img src="https://experienceleague-dev.corp.adobe.com/assets/img/left-rail-open.svg">`;
@nitin-rachabathuni If you can fix this and one other feedback, maybe we can merge the PR.

2023-10-25 06:27 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +        rightSectionWidth = main?.children?.[2]?.classList?.contains(
done @thomsebastin

2023-10-25 06:27 UTC, nitin-rachabathuni commented on scripts/scripts.js
> +  toggleElement.innerHTML = `<img src="https://experienceleague-dev.corp.adobe.com/assets/img/left-rail-open.svg">`;
done @thomsebastin

2023-10-25 06:34 UTC, thomsebastin commented on styles/styles.scss
> +      grid-row: 1/999999999999;
I haven't seen `grid-row` being used like this. I will check this with @ahmed-musallam to understand why this is needed.

2023-10-25 08:26 UTC, nitin-rachabathuni commented on styles/styles.scss
> +      grid-row: 1/999999999999;
Updated it @thomsebastin

2023-10-25 09:26 UTC, merged

2023-10-25 13:30 UTC, ahmed-musallam commented
@nitin-rachabathuni can you address the review item in a separate PR please

2023-10-25 14:15 UTC, nitin-rachabathuni commented
> @nitin-rachabathuni can you address the review item in a separate PR please

Sure @ahmed-musallam