feat: article meta blocks EXLM-180
adobe-experience-league/exlm pull request #45
Opened 2023-10-20 13:21 UTC by nitin-rachabathuni

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-180

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://exlm-180-article-meta--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management

2023-10-20 13:58 UTC, ahmed-musallam commented
@nitin-rachabathuni overall, I think decorating based on textContent is a bad idea.

In the converter, can we split this into 2 blocks instead? one for topic-list and one for created-for ?

2023-10-20 14:10 UTC, nitin-rachabathuni commented
> @nitin-rachabathuni overall, I think decorating based on textContent is a bad idea.
> 
> In the converter, can we split this into 2 blocks instead? one for topic-list and one for created-for ?

Hi @ahmed-musallam 
I had to do it based on textContent as id/classes/meta-tags are all getting stripped off. Went ahead with textContent as there is no other way. cc @thomsebastin @devisree29

2023-10-23 05:29 UTC, nitin-rachabathuni commented
> @nitin-rachabathuni overall, I think decorating based on textContent is a bad idea.
> 
> In the converter, can we split this into 2 blocks instead? one for topic-list and one for created-for ?

Hi @ahmed-musallam , I have updated the code, ty.

2023-10-25 07:43 UTC, Sivaramvt commented
@devisree29 could you please address this at the convertor side.

2023-10-25 10:25 UTC, thomsebastin requested changes

2023-10-25 10:25 UTC, thomsebastin commented on blocks/article-metadata-createdby/article-metadata-createdby.css
> +    color: #505050;
Please use variables @nitin-rachabathuni

2023-10-25 11:11 UTC, thomsebastin commented on blocks/article-metadata-createdby/article-metadata-createdby.css
> +    color: #505050;
@nitin-rachabathuni Also please include `SCSS` file as well.

2023-10-25 11:26 UTC, thomsebastin approved these changes

2023-10-25 11:29 UTC, merged