Featured card filters
adobe-experience-league/exlm pull request #535
Opened 2024-02-22 05:59 UTC by gauthamksn

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-1087

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.live
- After: https://feature-exlm-1087-featured--exlm--adobe-experience-league.hlx.live

2024-02-22 07:08 UTC, noormd08 requested changes
@gauthamksn Can we take it to generic place, so that we can integrate the same dropdown across application.

2024-02-22 12:17 UTC, devisree29 approved these changes

2024-02-22 13:22 UTC, noormd08 requested changes
As discussed, move the standalone functions inside and dropdown class & keep it as Static.
Also, add documentation comments to it.

2024-02-22 14:17 UTC, tprasad05 submitted a review, later dismissed

2024-02-23 08:39 UTC, noormd08 approved these changes
As discussed, please consider the below points for later implementation.
1. Pass it as object instead of multiple params.
2. Keyboard navigation
3. ID reference to be passed from parent

2024-02-23 08:39 UTC, merged