Language specific search redirection
adobe-experience-league/exlm pull request #543
Opened 2024-02-22 13:53 UTC by ruhisingh1

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Handled language-specific search redirection.

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.live/de/docs
- After: https://search-issue--exlm--adobe-experience-league.hlx.live/de/docs

2024-02-22 14:09 UTC, tprasad05 approved these changes

2024-02-22 14:46 UTC, devisree29 approved these changes

2024-02-23 07:46 UTC, noormd08 requested changes
As discussed, please move the language code to generic to avoid multiple loads.

2024-02-23 09:56 UTC, ruhisingh1 commented
> As discussed, please move the language code to generic to avoid multiple loads.

Fixed

2024-02-23 10:28 UTC, merged