fix: mini toc issues EXLM-293
adobe-experience-league/exlm pull request #66
Opened 2023-10-30 13:12 UTC by nitin-rachabathuni

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID:

Test URLs: https://jira.corp.adobe.com/browse/EXLM-293

- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://bugfix-exlm-293--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet

2023-10-31 06:38 UTC, thomsebastin approved these changes
Looks good. Left two comments to address.

2023-10-31 06:38 UTC, thomsebastin commented on blocks/mini-toc/mini-toc.js
> +          const anchor = anchors[0].parentElement;
Maybe put a check here to ensure `anchor[0]` exists.

2023-10-31 06:38 UTC, thomsebastin commented on blocks/mini-toc/mini-toc.js
> +            const anchorStylyes = getComputedStyle(anchor);
there is a typo here, should be `anchorStyles`?

2023-10-31 06:46 UTC, thomsebastin commented
@nitin-rachabathuni Just a suggestion, it is always recommended to have same page in `before` and `after` section of PR description so that it's easy to verify the changes.

2023-10-31 07:27 UTC, thomsebastin requested changes
The TOC is not appearing on the page. Looks like the converter is sending only one section now. We need to fix this before we can merge.

2023-10-31 07:30 UTC, nitin-rachabathuni commented on blocks/mini-toc/mini-toc.js
> +          const anchor = anchors[0].parentElement;
We have ` if (anchors.length > 0) { ` check in line 31.

2023-11-02 10:06 UTC, thomsebastin approved these changes

2023-11-02 10:15 UTC, merged