EXLM-83: accordion block
adobe-experience-league/exlm pull request #72
Opened 2023-10-31 02:08 UTC by gandal-adobe

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: EXLM-83

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://feature-exlm-83-accordion--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management

2023-10-31 06:57 UTC, thomsebastin commented on blocks/accordion/accordion.scss
> +  padding-bottom: 16px;
This could just be `padding: 16px`

2023-11-01 18:54 UTC, ahmed-musallam requested changes

2023-11-01 18:54 UTC, ahmed-musallam commented on blocks/accordion/accordion.js
> +    pElement.innerHTML = block.innerHTML;
Block content should not live in a `<p>`, rather it should be copied into `details` as-is

2023-11-02 05:33 UTC, gandal-adobe commented on blocks/accordion/accordion.js
> +    pElement.innerHTML = block.innerHTML;
modified to:
```
    // next div element(s) form the accordion details
    Array.from(block.children).forEach((element) => {
        detailsElement.appendChild(element);
    });
```

2023-11-03 20:13 UTC, ahmed-musallam commented
@gandal-adobe LGTM

2023-11-03 20:13 UTC, ahmed-musallam approved these changes

2023-11-07 12:27 UTC, thomsebastin approved these changes

2023-11-07 12:27 UTC, merged