feat: mini-toc changes for mobile exlm-1368
adobe-experience-league/exlm pull request #801
Opened 2024-04-23 10:03 UTC by nitin-rachabathuni

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-1368

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
- After: https://feat-exlm-1368--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article

2024-04-23 12:23 UTC, noormd08 approved these changes

2024-04-23 12:24 UTC, noormd08 requested changes
Can’t we reuse the dropdown script which we created earlier?

2024-04-24 05:58 UTC, nitin-rachabathuni commented
> Can’t we reuse the dropdown script which we created earlier?


For Mini TOC mobile/tab we cannot use the existing dropdown script, as look/feel/behaviour is different here Noor.

2024-04-25 14:02 UTC, noormd08 commented on scripts/dropdown/dropdown.js
> +};
Can you please the generic name in the variant instead of MINI_TOC

2024-04-25 14:03 UTC, noormd08 commented on scripts/dropdown/dropdown.js
> +  constructor(parentFormElement, defaultValue, optionsArray, variant) {
Please default variant here itself

2024-04-29 02:25 UTC, noormd08 commented on blocks/mini-toc/mini-toc.css
> +  overflow: visible;
Any reason for making visible? Ideally it should be auto in case we want to have a scroll on need basis right?

2024-04-29 03:01 UTC, nitin-rachabathuni commented on blocks/mini-toc/mini-toc.css
> +  overflow: visible;
This is for mobile where we have to see the internal contents of the mini-toc in form of a dropdown. We are overriding it for higher resolutions.
And this is not working with `overflow: auto`

2024-04-29 03:10 UTC, nitin-rachabathuni commented on scripts/dropdown/dropdown.js
> +};
done Noor

2024-04-29 03:10 UTC, nitin-rachabathuni commented on scripts/dropdown/dropdown.js
> +  constructor(parentFormElement, defaultValue, optionsArray, variant) {
done done

2024-04-29 03:11 UTC, noormd08 approved these changes

2024-04-29 03:12 UTC, merged