Feat exlm 1349
adobe-experience-league/exlm pull request #807
Opened 2024-04-23 18:01 UTC by mayukhs2904

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-1349

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.live
- After: https://feat-exlm-1349--exlm--adobe-experience-league.hlx.live

2024-04-24 09:28 UTC, devisree29 approved these changes

2024-04-24 11:19 UTC, noormd08 commented on blocks/social-share-block/social-share-block.css
> +}
Please format the CSS. Add space before curly bracket {

2024-04-24 11:21 UTC, noormd08 commented on blocks/social-share-block/social-share-block.js
> +
SVG to be added as HTML Tag
const icon = '<span class="icon icon-**name**"></span>';

2024-04-24 11:21 UTC, noormd08 requested changes
Please check the review comments

2024-04-30 06:58 UTC, noormd08 commented on blocks/social-share-block/social-share-block.js
> +      value: 'facebook',
Please keep this one as ID and above one as Label

2024-04-30 07:05 UTC, noormd08 commented on blocks/social-share-block/social-share-block.js
> +                </div>
Can you simplify this to a single call for getObjectById?

2024-04-30 07:42 UTC, noormd08 commented on blocks/social-share-block/social-share-block.js
> +                <div class="social-share-item">
Do we need div tag inside the anchor? Can't we directly use the class name in anchor

2024-04-30 10:37 UTC, noormd08 approved these changes

2024-04-30 10:38 UTC, merged