Role cards UE & FE changes
adobe-experience-league/exlm pull request #888
Opened 2024-05-22 04:46 UTC by mayukhs2904

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-1506

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page
- After: https://feat-exlm-1506--exlm--adobe-experience-league.hlx.page

2024-05-22 10:35 UTC, gauthamksn requested changes

2024-05-22 10:35 UTC, gauthamksn commented on blocks/role-cards/role-cards.css
> +@media (min-width: 601px) and (max-width: 900px) {
Please use standard media-queries. 
Default - Mobile
(min-width: 600) - Tablet
(min-width: 900) - Desktop

2024-05-22 10:35 UTC, gauthamksn commented on blocks/role-cards/role-cards.css
> +@media (max-width: 600px) {
use (min-width: 600) for tablet.

2024-05-22 12:59 UTC, gauthamksn approved these changes
LGTM

2024-05-22 13:45 UTC, ruhisingh1 approved these changes

2024-05-23 07:19 UTC, noormd08 approved these changes

2024-05-23 07:20 UTC, merged