fix: article metadata mobile issues & hide mini-toc section on mobile EXLM-286, EXLM-293
adobe-experience-league/exlm pull request #95
Opened 2023-11-07 15:58 UTC by nitin-rachabathuni

Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-286
https://jira.corp.adobe.com/browse/EXLM-293

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/journey-optimizer-learn/tutorials/introduction-to-journey-optimizer/mobile-capabilities-for-developers
- After: https://bugfix-exlm-286-article-tag--exlm--adobe-experience-league.hlx.page/docs/journey-optimizer-learn/tutorials/introduction-to-journey-optimizer/mobile-capabilities-for-developers

2023-11-08 11:03 UTC, thomsebastin requested changes

2023-11-08 11:03 UTC, thomsebastin commented on blocks/article-metadata-createdby/article-metadata-createdby.scss
> +  line-height: 15.6px;
Can tis line-height be a variable? I have been seeing this value quite often now.

2023-11-08 11:03 UTC, thomsebastin commented on styles/styles.scss
> +      }
are these changes related to this PR?

2023-11-08 11:05 UTC, thomsebastin commented
Please merge with latest `main` and see if the performance score changes.

2023-11-08 13:26 UTC, nitin-rachabathuni commented on styles/styles.scss
> +      }
Yes Thomas, these are related to EXLM-293

2023-11-08 13:58 UTC, nitin-rachabathuni commented on styles/styles.scss
> +  --non-spectrum-article-dark-gray: #505050;
I have already updated all the references of these variables @thomsebastin 
--non-spectrum-article-light-gray: #d3d3d3;
  --non-spectrum-article-dark-gray: #505050;

2023-11-08 14:04 UTC, thomsebastin commented
I think this particular page and other pages where video is loaded seems to have some performance issues as it is blocking the main thread. We may have to look at it.
cc: @ahmed-musallam

2023-11-09 08:16 UTC, noormd08 approved these changes

2023-11-09 08:17 UTC, noormd08 commented on styles/styles.scss
> +    }
This can lead to override throughout application.

2023-11-09 12:45 UTC, noormd08 approved these changes

2023-11-09 12:47 UTC, merged